theme: jekyll-theme-cayman
title:        Школа Машинного Обучения
tagline:      МФТИ
author:
  name:       "mlphystech@gmail.com"
  url:        mailto:mlphystech@gmail.com
vk:
  name:       vk.com/mlschl
  url:        https://vk.com/mlschl
